# Deployment for pinger app v2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinger-v2
  namespace: default
  labels:
    app: pinger
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
      version: v2
  template:
    metadata:
      labels:
        app: pinger
        version: v2
    spec:
      containers:
      - name: pinger
        image: krishnareddy1239/v2
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
---
# Service for ping app v2
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pinger
    version: v2
  name: pinger-v2-service
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: pinger
    version: v2
  sessionAffinity: None
  type: ClusterIP